server:
  port: 9188
spring:
  application:
    name: coding-config-server
  cloud:
    config:
      server:
        git:
          # Spring Cloud Config支持的访问规则：
          # 1. /{application}/{profile}[/{label}]
          # 2. /{application}-{profile}.yml
          # 3. /{label}/{application}-{profile}.yml
          uri: https://github.com/csulwk/coding-config.git
          # 使用占位符来设定搜索路径
          search-paths: '{application}'
          # username和password必须配对使用，公开库可以不用填写
          username:
          password:
